repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: flake8
  - repo: local
    hooks:
      - id: scripts
        name: Commit Scripts
        entry: hooks.sh
        language: script
