debug: true
listen_address: "0.0.0.0"
port: 8080
mode: bird # frr|bird
# secret: dont4get
secret: TestSecret12345
# commands:
#   frr:
#     ipv4_default:
#       bgp_aspath: show bgp ipv4 unicast quote-regexp "{target}"
#       bgp_community: show bgp ipv4 unicast community {target}
#       bgp_route: show bgp ipv4 unicast {target} | exclude pathid:|Epoch
#       ping: ping {target} repeat 5 source {source}
#       traceroute: traceroute {target} timeout 1 probe 2 source {source}
#     ipv4_vpn:
#       bgp_aspath: show bgp vpnv4 unicast vrf {vrf} quote-regexp "{target}"
#       bgp_community: show bgp vpnv4 unicast vrf {vrf} community {target}
#       bgp_route: show bgp vpnv4 unicast vrf {vrf} {target}
#       ping: ping vrf {vrf} {target} repeat 5 source {source}
#       traceroute: traceroute vrf {vrf} {target} timeout 1 probe 2 source {source}
#     ipv6_default:
#       bgp_aspath: show bgp ipv6 unicast quote-regexp "{target}"
#       bgp_community: show bgp ipv6 unicast community {target}
#       bgp_route: show bgp ipv6 unicast {target} | exclude pathid:|Epoch
#       ping: ping {afi} {target} repeat 5 source {source}
#       traceroute: traceroute ipv6 {target} timeout 1 probe 2 source {source}
#     ipv6_vpn:
#       bgp_aspath: show bgp vpnv6 unicast vrf {vrf} quote-regexp "{target}"
#       bgp_community: show bgp vpnv6 unicast vrf {vrf} community {target}
#       bgp_route: show bgp vpnv6 unicast vrf {vrf} {target}
#       ping: ping vrf {vrf} {target} repeat 5 source {source}
#       traceroute: traceroute vrf {vrf} {target} timeout 1 probe 2 source {source}
